#!/usr/bin/bash

git submodule add ssh://aur@aur4.archlinux.org/$1.git AUR/$1
cd AUR/$1
cp -r ../../$1/* .
fish
mksrcinfo
git add .
git commit -m 'Initial import'
git push -u origin master
cd ../..
git submodule add ssh://aur@aur4.archlinux.org/$1.git AUR/$1

