#!/bin/bash

isnumber() { test "$1" && printf '%f' "$1" &> /dev/null; }

cmd="$1"
if [[ -z "$cmd" ]]; then
  cmd="."
fi

if [ ! -f "$cmd" ]; then
  if isnumber $cmd; then
    cmd="http://localhost:$cmd/"
  elif which $cmd &> /dev/null; then
    cmd=$(which $cmd)
  fi
fi

mimeo "$cmd" &> /dev/null &
